# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0002_auto_20170825_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_books',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='book',
            name='liked',
            field=models.ManyToManyField(related_name='users', to='likes_books.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
